Handle migration in the connector
Crewdle/mist-connector-indexed-db pull request #1
Opened 2024-03-21 18:46 UTC by vlamanna

2024-03-21 18:49 UTC, ThomBoul approved these changes

2024-03-22 18:24 UTC, Mikechaos requested changes
Small changes and something we missed in the initial implementation that we need to fix

2024-03-22 18:24 UTC, Mikechaos commented on src/index.ts
> +          for (const table in db.objectStoreNames) {
This needs to be moved outside the for loop

2024-03-22 18:24 UTC, Mikechaos commented on src/index.ts
> +      throw new Error(`Table '${tableName}' does not exist`);
Actually Vince pointed out that we cannot create tables in IndexedDB so this should always throw an `operation unsupported` error

2024-03-25 15:40 UTC, Mikechaos approved these changes

2024-03-25 15:40 UTC, merged